Middleware support for Muffin/Throttle
UseMuffin/Throttle pull request #22
Opened 2017-03-08 20:18 UTC by chrisShick

I have added the middleware class and the tests. Let me know if you want to change the directory location and if I did the test to your liking.

2017-03-08 20:52 UTC, ADmad requested changes

2017-03-08 20:52 UTC, ADmad commented on .gitignore
> +/.idea
This should go to your environment's global ignore file. Please don't modify this repo's .gitignore.

2017-03-08 20:52 UTC, ADmad commented on composer.json
> +        "cakephp/cakephp": "3.4.*",
Keep this unchanged, highest available cakephp release supported on the platform will be automatically used.

2017-03-08 20:52 UTC, ADmad commented on composer.json
> +        "phpunit/phpunit": "^5.7|^6.0"
Change to "<6.0" so that the test suite runs for older CakePHP version on PHP 5.5.

2017-03-08 20:52 UTC, ADmad commented on tests/TestCase/Middleware/ThrottleMiddlewareTest.php
> +        $this->skipIf(!function_exists('apcu_store'), 'APCu is not installed or configured properly.');
Also skip the tests for CakePHP < 3.3 as middleware support is not available before that. I want to add this middleware without bumping the plugin's CakePHP version dependency.

2017-03-08 22:39 UTC, chrisShick commented
@ADmad Alright :D just fixed everything up.

2017-03-09 05:35 UTC, ADmad commented
Please rebase your branch onto latest upstream master. I have made fixes to get the builds running on various PHP versions.

2017-03-09 05:40 UTC, ADmad requested changes

2017-03-09 05:40 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +
Extra empty line

2017-03-09 05:40 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +
Extra empty line

2017-03-09 05:40 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +
Extra empty line

2017-03-09 05:40 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +     * @param ServerRequestInterface $request Request object
Please use full namespace like `\Psr\Http\Message\ServerRequestInterface` starting with backslash for all type declarations in docblocks.

2017-03-09 05:40 UTC, ADmad commented on tests/TestCase/Middleware/ThrottleMiddlewareTest.php
> +        $this->skipIf(version_compare(Configure::version(), '3.3') == -1 ? true : false);
You have used `setConfig()` in the middleware which is not available in `3.3`, so need to bump this check to `3.4`.

2017-03-09 06:09 UTC, chrisShick commented
This build failed on Muffin\Throttle\Test\TestCase\Routing\Filter\ThrottleFilterTest::testTouchMethod
Failed asserting that 3 matches expected 1.

I believe this is might be because the Cache config is not dropping properly and the two atomic updates from the Middleware is still hanging around?

2017-03-09 06:49 UTC, ADmad commented
> I believe this is might be because the Cache config is not dropping properly and the two atomic updates from the Middleware is still hanging around?

Delete the particular key before dropping cache config at end of the test methods in both the dispatch filter and middlware tests.

2017-03-09 07:01 UTC, ADmad requested changes

2017-03-09 07:01 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +     * @return ResponseInterface
Full namespace missing.

2017-03-09 07:01 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +     * @return \Cake\Cache\Cache
Incorrect return type.

2017-03-09 07:01 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +     * @return ResponseInterface
Full namespace missing

2017-03-09 07:03 UTC, ADmad commented on tests/TestCase/Middleware/ThrottleMiddlewareTest.php
> +    public function getReflection($object, $method = false, $property = false)
Should be protected method

2017-03-09 07:07 UTC, chrisShick commented on src/Middleware/ThrottleMiddleware.php
> +     * @return \Cake\Cache\Cache
What return type would this be? It looks as if that is exactly how it is returned??

2017-03-09 07:08 UTC, ADmad commented on tests/TestCase/Middleware/ThrottleMiddlewareTest.php
> +            'limit' => 0
Please do the test with limit 1 and assert that first request goes through and headers are set. As seen [here](https://codecov.io/gh/UseMuffin/Throttle/src/a8d4f87348cc09226238fef6546cc1c00759d3bc/src/Middleware/ThrottleMiddleware.php#L97) code coverage is missing for this case.

2017-03-09 07:09 UTC, bravo-kernel commented on tests/TestCase/Middleware/ThrottleMiddlewareTest.php
> +    public function getReflection($object, $method = false, $property = false)
That's an historical bad on my behalf whilst I was learning how to test, I dropped this in favor of https://github.com/FriendsOfCake/cakephp-test-utilities

2017-03-09 07:10 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +     * @return \Cake\Cache\Cache
The method returns value of `Cache::increment()` so return type should be same as `Cache::increment()`'s which is `mixed`.

2017-03-09 07:32 UTC, chrisShick commented on tests/TestCase/Middleware/ThrottleMiddlewareTest.php
> +            'limit' => 0
Alright, I believe I just did a few asserts for both test cases. Let me know if I did that correctly.

2017-03-09 07:36 UTC, chrisShick commented
Whoop Whoop!! Looks like I finally have a passing build lol

2017-03-09 07:45 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +        $response = $next($request, $response);
These last 2 statements should be swapped. Calling the next middleware in queue should be the last statement.

2017-03-09 07:50 UTC, chrisShick commented on src/Middleware/ThrottleMiddleware.php
> +        $response = $next($request, $response);
According to the cake [documentation](https://book.cakephp.org/3.0/en/controllers/middleware.html#creating-middleware), when modifying the response we are suppose to modify after calling next. Is this wrong?

2017-03-09 07:54 UTC, ADmad commented on src/Middleware/ThrottleMiddleware.php
> +        $response = $next($request, $response);
My mistake, docs are correct.

2017-03-09 07:55 UTC, chrisShick commented on src/Middleware/ThrottleMiddleware.php
> +        $response = $next($request, $response);
I came across that because during development I made that same assumption and it wouldn't return correctly lol.

2017-03-09 07:56 UTC, ADmad commented
There's quite a bit of code duplication between the dispatchfilter and the middleware. It would be nice to put the common methods in a trait.

Please also about the readme regarding middleware usage.

2017-03-09 07:59 UTC, chrisShick commented
I was actually thinking the same thing in regards to placing it in a trait. I just did not know at the time what your plans were with both. I am down to write the trait as well :D and update the readme

2017-03-09 08:46 UTC, chrisShick commented
@ADmad The only issue I see with trying to create a trait is the use of config and setConfig/getConfig. Both are used so much that trying to create a trait become difficult. Unless we want to just stick with config (despite the depreciation).

2017-03-09 11:43 UTC, ADmad commented
One option to deal with that is to add getConfig(), setConfig() to the dispatch filter :)

2017-03-09 17:54 UTC, chrisShick commented
@ADmad Alright, I just attempted the ThrottleTrait :D Let me know what you think!

2017-03-09 18:30 UTC, ADmad reviewed
Travis job on PHP 5.5 is failing.

2017-03-09 18:30 UTC, ADmad commented on README.md
> +\
Why the backslashes?

2017-03-09 18:30 UTC, ADmad commented on README.md
> +use Muffin\Throttle\Middlware\ThrottleMiddleware.php;
Drop the `.php` :)

2017-03-09 18:30 UTC, ADmad commented on README.md
> +        'identifier' => function (Request $request) {
Typehint should be `ServerRequestInterface`

2017-03-09 19:09 UTC, chrisShick commented
@ADmad I am unsure of how to fix the 5.5 issue in order to keep backward compatibility with the DispatchFilter. I would have to update the DispatchFilter tests to use the ServerRequestInterface.

2017-03-09 19:22 UTC, chrisShick commented
Unless I put another if statement in to change it.

2017-03-09 19:25 UTC, chrisShick commented
Unless we do not specify the request type at all.

2017-03-09 19:41 UTC, ADmad commented
Removing the typehint did it, but there's another error now, please check.

2017-03-09 21:19 UTC, chrisShick commented
Boom! All checks have passed!

2017-03-10 07:16 UTC, bravo-kernel commented
Good job mr. @chrisShick

2017-03-10 15:50 UTC, chrisShick commented
@bravo-kernel It is more like thanks to you and @ADmad

2017-03-10 19:17 UTC, ADmad approved these changes

2017-03-10 19:18 UTC, merged

2017-03-10 19:20 UTC, bravo-kernel commented
Job well done and time I was able to spend on other stuff so much obliged mr. @chrisShick, this will be my first middleware very soon 💯

2017-03-10 19:24 UTC, chrisShick commented
@bravo-kernel thanks! That is exciting to hear!

I am actually in the process of creating a [CakeMiddlewares](https://github.com/chrisShick/CakeMiddlewares) plugin for common middlewares that I feel would be useful for people and are easily integrated into any Cake 3.4.x or greater project. :D